trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: variables

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "TF_BUILD                                : $env:TF_BUILD"
      Write-Host "TF_BUILD_BUILDURI                       : $env:TF_BUILD_BUILDURI"
      Write-Host "TF_BUILD_SOURCESDIRECTORY               : $env:TF_BUILD_SOURCESDIRECTORY"

      Write-Host "BUILD_BUILDURI                          : $env:BUILD_BUILDURI"
      Write-Host "BUILD_SOURCESDIRECTORY                  : $env:BUILD_SOURCESDIRECTORY"

      Write-Host "Build.SourcesDirectory                  : $(Build.SourcesDirectory)"

- task: SonarCloudPrepare@2
  inputs:
    SonarCloud: 'SonarCloud - Costin Z Token'
    organization: 'costin-zaharia-sonarsource'
    scannerMode: 'MSBuild'
    # msBuildVersion: '9.0.1.102776'
    projectKey: 'DevOps-Extension'
    projectName: 'DevOps-Extension'
    extraProperties: |
      sonar.verbose=true

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code coverage"'

- task: SonarCloudAnalyze@2
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'