# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "TF_BUILD_BUILDURI                       : $env:TF_BUILD_BUILDURI"
      Write-Host "TF_BUILD_SOURCESDIRECTORY               : $env:TF_BUILD_SOURCESDIRECTORY"

      Write-Host "BUILD_BUILDURI                          : $env:BUILD_BUILDURI"
      Write-Host "BUILD_SOURCESDIRECTORY                  : $env:BUILD_SOURCESDIRECTORY"

      Write-Host "Build.SourcesDirectory                  : $(Build.SourcesDirectory)"

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloud - Costin Z Token'
    organization: 'costin-zaharia-sonarsource'
    scannerMode: 'dotnet'
    projectKey: 'DevOps-Extension'
    projectName: 'DevOps-Extension'
    extraProperties: |
      sonar.verbose=true

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code coverage"'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
