# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: TestVarGroup

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    $env:Var1
    $env:Secret1
  displayName: "Output env"
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Peach'
    scannerMode: 'MSBuild'
    projectKey: 'SampleNetSolution'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code coverage"'
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'
    
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
