trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: variables

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "TF_BUILD                                : $env:TF_BUILD"
      Write-Host "TF_BUILD_BUILDURI                       : $env:TF_BUILD_BUILDURI"
      Write-Host "TF_BUILD_SOURCESDIRECTORY               : $env:TF_BUILD_SOURCESDIRECTORY"

      Write-Host "BUILD_BUILDURI                          : $env:BUILD_BUILDURI"
      Write-Host "BUILD_SOURCESDIRECTORY                  : $env:BUILD_SOURCESDIRECTORY"

      Write-Host "Build.SourcesDirectory                  : $(Build.SourcesDirectory)"

      cd "$(Pipeline.Workspace)"

      dotnet ./s/scanner/SonarScanner.MSBuild.dll begin /o:"costin-sonar" /k:"costin-sonar_sample-dotnet" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.token="$(SONAR_TOKEN)" /d:sonar.verbose=true

      dotnet test ./s/SampleNetSolution.sln --collect "Code coverage"

      dotnet ./s/scanner/SonarScanner.MSBuild.dll end /d:sonar.login="$(SONAR_TOKEN)"